namespace _UTIL_
{
    public enum LayerBits : byte
    {
        Default = 0,
        TransparentFX = 1,
        Ignore_Raycast = 2,
        Water = 4,
        UI = 5,
        ignore = 6,
        cube_UI = 7,
        PostProcessing = 8,
        Editor = 9,
        phs_art = 10,
        vsl_art = 11,
        art = 12,
        stairs = 13,
        wall = 14,
        cover = 15,
        climb = 16,
        ground = 17,
        terrain = 18,
        grav = 19,
        intr = 20,
        weapon = 21,
        bonus = 22,
        vehicle = 23,
        projectile = 24,
        ragdoll_car = 26,
        ragdoll_phs = 27,
        ragdoll_vsl = 28,
        player = 29,
        player_remote = 30,
        player_trigger = 31,
    }


    [System.Flags]
    public enum LayerMasks
    {
        Default = 1 << LayerBits.Default,
        TransparentFX = 1 << LayerBits.TransparentFX,
        Ignore_Raycast = 1 << LayerBits.Ignore_Raycast,
        Water = 1 << LayerBits.Water,
        UI = 1 << LayerBits.UI,
        ignore = 1 << LayerBits.ignore,
        cube_UI = 1 << LayerBits.cube_UI,
        PostProcessing = 1 << LayerBits.PostProcessing,
        Editor = 1 << LayerBits.Editor,
        phs_art = 1 << LayerBits.phs_art,
        vsl_art = 1 << LayerBits.vsl_art,
        art = 1 << LayerBits.art,
        stairs = 1 << LayerBits.stairs,
        wall = 1 << LayerBits.wall,
        cover = 1 << LayerBits.cover,
        climb = 1 << LayerBits.climb,
        ground = 1 << LayerBits.ground,
        terrain = 1 << LayerBits.terrain,
        grav = 1 << LayerBits.grav,
        intr = 1 << LayerBits.intr,
        weapon = 1 << LayerBits.weapon,
        bonus = 1 << LayerBits.bonus,
        vehicle = 1 << LayerBits.vehicle,
        projectile = 1 << LayerBits.projectile,
        ragdoll_car = 1 << LayerBits.ragdoll_car,
        ragdoll_phs = 1 << LayerBits.ragdoll_phs,
        ragdoll_vsl = 1 << LayerBits.ragdoll_vsl,
        player = 1 << LayerBits.player,
        player_remote = 1 << LayerBits.player_remote,
        player_trigger = 1 << LayerBits.player_trigger,
    }
}